export default {
  GET_NAVIGATOR: 'GET_NAVIGATOR',
  SET_NAVIGATOR: 'SET_NAVIGATOR',
  NAVIGATE: 'NAVIGATE',
  GO_BACK: 'GO_BACK',

  SET_USER_POSITION: 'SET_USER_POSITION',
  GET_USER_POSITION: 'GET_USER_POSITION',

  TOGGLE_DRAWER: 'TOGGLE_DRAWER',
  OPEN_DRAWER: 'OPEN_DRAWER',
  CLOSE_DRAWER: 'CLOSE_DRAWER',
};