export default {
  SET_NAVIGATOR: 'SET_NAVIGATOR',
  NAVIGATE: 'NAVIGATE',
  GO_BACK: 'GO_BACK',

  SET_USER_POSITION: 'SET_USER_POSITION',

  TOGGLE_DRAWER: 'TOGGLE_DRAWER',
  OPEN_DRAWER: 'OPEN_DRAWER',
  CLOSE_DRAWER: 'CLOSE_DRAWER',

  SET_RADIUS: 'SET_RADIUS',
  SET_MAP_TYPE: 'SET_MAP_TYPE',
};