export default {
  INITIALIZE_NAVIGATION: 'INITIALIZE_NAVIGATION',
  NAVIGATE: 'NAVIGATE',
  GO_BACK: 'GO_BACK',
  SET_PARAMS: 'SET_PARAMS',

  SET_USER_POSITION: 'SET_USER_POSITION',

  TOGGLE_DRAWER: 'TOGGLE_DRAWER',
  OPEN_DRAWER: 'OPEN_DRAWER',
  CLOSE_DRAWER: 'CLOSE_DRAWER',

  SET_SETTINGS_DEFAULTS: 'SET_SETTINGS_DEFAULTS',
  SET_RADIUS: 'SET_RADIUS',
  SET_MAP_TYPE: 'SET_MAP_TYPE',
  TOGGLE_FETCH_ON_POSITION_CHANGE: 'TOGGLE_FETCH_ON_POSITION_CHANGE',
  TOGGLE_FETCH_PERIODICALLY: 'TOGGLE_FETCH_PERIODICALLY',
  SET_FETCHING_PERIOD: 'SET_FETCHING_PERIOD',

  SET_PARKING_TYPES: 'SET_PARKING_TYPES',
  SET_PARKING_TAKEN_FOR_SLOTS: 'SET_PARKING_TAKEN_FOR_SLOTS',
  SET_USER_ADDRESSES: 'SET_USER_ADDRESSES',
  NEW_ADDRESS: 'NEW_ADDRESS',

  SET_AUTH_DEFAULTS: 'SET_AUTH_DEFAULTS',
  SET_IS_LOGGED_IN: 'SET_IS_LOGGED_IN',
  ON_REGISTERED: 'ON_REGISTERED',
  SET_USERNAME: 'SET_USERNAME',
  SET_POINTS: 'SET_POINTS'
};